# Generated by Django 4.2.6 on 2023-10-21 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_p_key_box_private_key_box_public_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="box",
            name="description",
        ),
    ]
