# Generated by Django 4.2.6 on 2023-10-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_box_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="name",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
